# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://feliperottnerrodrigues:root@taskgreen.wqod5xy.mongodb.net/taskgreen-api?retryWrites=true&w=majority&appName=taskgreen

# File upload settings
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Server settings
server.port=8080

# Swagger settings
springdoc.swagger-ui.path=/swagger-documents.html
springdoc.api-docs.path=/api-task-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.title=API de Tarefas Pessoais