# ==============================
# CONFIGURAÇÃO PARA BANCO MYSQL
# ==============================

spring.datasource.url=jdbc:mysql://localhost:3306/tarefas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Atualiza as tabelas automaticamente conforme as entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-documents.html
springdoc.api-docs.path=/api-task-docs
springdoc.swagger-ui.operationsSorter=method

# Limite máximo para upload de um único arquivo
spring.servlet.multipart.max-file-size=50MB

# Limite máximo para o tamanho total da requisição (vários arquivos, dados, etc)
spring.servlet.multipart.max-request-size=50MB

upload.diretorio=uploads/


