const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, backgroundColor: '#f9fcff' },
  logo: { fontSize: 26, fontWeight: 'bold', color: '#00c6ad' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  date: { fontSize: 20, fontWeight: 'bold' },
  addButton: { backgroundColor: '#a7e1f7', padding: 10, borderRadius: 20 },
  addText: { fontWeight: 'bold' },
  dayItem: { marginRight: 12, alignItems: 'center', padding: 10, backgroundColor: '#e0f7fa', borderRadius: 10 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', marginVertical: 10 },
  taskCard: { backgroundColor: '#fff', padding: 15, borderRadius: 10, marginBottom: 10, elevation: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  taskTitle: { fontWeight: 'bold' },
  dots: { padding: 5 },
  searchIcon: { position: 'absolute', bottom: 20, right: 20 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalContainer: { backgroundColor: '#fff', padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20 },
  modalButton: { paddingVertical: 10 },
  modalText: { fontSize: 18 },
});
